name: Plugin Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: 'Version (x.x.x)'
        required: true
        default: 'continuous'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install Hetu dev tools
        run: dart pub global activate hetu_script_dev_tools

      - name: Compile plugin
        run: mkdir -p build && hetu compile src/plugin.ht build/plugin.out

      - name: Archive plugin
        run: |
          mkdir -p build/archive
          cp plugin.json build/plugin.out assets/logo.png build/archive/
          cd build/archive
          zip -r plugin.zip ./
          cd ../..
          mv build/archive/plugin.zip build/plugin.smplug

      - name: Upload plugin artifact
        uses: actions/upload-artifact@v4
        with:
          name: plugin-smplug
          path: build/plugin.smplug

      - name: Upload to release (${{ github.event.inputs.version }})
        if: github.event_name == 'workflow_dispatch'
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.inputs.version }}
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          omitPrereleaseDuringUpdate: true
          allowUpdates: true
          artifacts: build/plugin.smplug
